# Generated by Django 4.2.6 on 2023-11-27 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0002_cart_remove_customer_password_remove_user_gender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='delivery',
        ),
        migrations.AddField(
            model_name='order',
            name='placedorder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='shipped',
            field=models.BooleanField(default=False),
        ),
    ]
