# Generated by Django 4.2.6 on 2023-11-27 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0004_order_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliverydate',
            field=models.DateField(null=True),
        ),
    ]
