# Generated by Django 4.2.6 on 2023-11-29 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0006_alter_cart_cart_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paymentstatus',
            field=models.BooleanField(default=True),
        ),
    ]
